model_comment: 'donors choose example'
input_path: "../../examples/donors/data_small.csv"
project_path: "../../examples/donors/"
output_path: "../../examples/donors/results.csv"

random_seed: 23895478

user_metadata:
  author: 'Tim Hannifan'
  etl_date: '2019-06-02'

temporal_config:
    start_time: '2012-01-01'
    end_time: '2014-01-01'
    prediction_windows: [6]
    model_update_frequency: 6

label_config:
    name: 'not_funded'
    include_missing_labels_in_train_as: False


model_config:
    # 'sklearn.dummy.DummyClassifier':
    #     strategy: [most_frequent]
    'sklearn.ensemble.ExtraTreesClassifier':
        n_estimators: [5]
        criterion: [entropy]
        max_depth: [1,2]
        min_samples_split: [2]

scoring:
  testing_metric_groups:
    -
      metrics: ['precision@', 'recall@']
      thresholds:
        percentiles: [1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 50.0]
        top_n: [10, 25]
  training_metric_groups:
    -
      metrics: ['accuracy']
    -
      metrics: ['precision@', 'recall@']
      thresholds:
        percentiles: [1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 50.0]
        top_n: [10, 25]

feature_generation:
    -
        # Categorical features. The column given can be of any type, but the
        # choices must comparable to that type for equality within SQL
        # The result will be one feature for each choice/metric combination
        categoricals:
            -
                column: 'poverty'
                imputation:
                    sum:
                        type: 'null_category'
                    max:
                        type: 'mean'
                    choice_query: 'select distinct poverty from semantic.entities'
                metrics:
                    - 'sum'
            -
                column: 'shape'
                imputation:
                    all:
                        type: 'zero'
                choice_query: 'select distinct shape from cool_stuff'
                metrics:
                    - 'sum'
